-- ============================================================================
-- F.I.R.E — Bulk competitions import (50 real, verified competitions)
-- All pre-approved. Fixed UUIDs + `on conflict (id) do nothing` = safe to re-run.
-- Run AFTER schema.sql. club_id is null (not tied to a F.I.R.E club).
-- Dates are relative to current_date so listings always read as "upcoming";
-- update to the real annual deadlines when known.
-- Duplicates of existing seed.sql rows (SSEF, SMO, Conrad, F1 in Schools,
-- UOB Painting of the Year, National Schools Debating) are intentionally omitted.
-- ============================================================================

insert into public.competitions
  (id, title, description, category, organizer, deadline, event_date, eligibility, registration_link, prize, format, region, club_id, is_approved, is_featured)
values
  -- ---- Science / STEM / Math / Tech ----------------------------------------
  ('33333333-0000-0000-0000-000000000001',
   'Singapore Junior Physics Olympiad (SJPO)',
   'A national physics competition organised by the Institute of Physics Singapore for upper secondary students. It tests conceptual understanding and problem-solving and serves as an entry point into Singapore''s physics olympiad pathway.',
   'Science', 'Institute of Physics Singapore (IPS)',
   (current_date + interval '18 days')::date, (current_date + interval '48 days')::date,
   'Secondary 3-4 (and equivalent)', 'https://ipssingapore.org/events/SJPO.html',
   'Gold/Silver/Bronze certificates', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000002',
   'Singapore Junior Chemistry Olympiad (SJChO)',
   'An annual chemistry competition run by the Singapore National Institute of Chemistry for secondary students with an interest in chemistry. It assesses theoretical chemistry knowledge and rewards top performers with medals.',
   'Science', 'Singapore National Institute of Chemistry (SNIC)',
   (current_date + interval '22 days')::date, (current_date + interval '52 days')::date,
   'Secondary 3-5 (age <=17)', 'https://www.snic.org.sg/index.php/event/sjcho/sjcho-competition-details',
   'Gold/Silver/Bronze medals', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000003',
   'Singapore Junior Biology Olympiad (SJBO)',
   'A biology competition for upper secondary students organised by the Singapore Institute of Biology. Started in 2016, it complements the senior Singapore Biology Olympiad with a theory round testing biology fundamentals.',
   'Science', 'Singapore Institute of Biology (SIBiol)',
   (current_date + interval '14 days')::date, (current_date + interval '40 days')::date,
   'Secondary 2-4 (ages 14-16)', 'https://sjbo.sibiol.org.sg/registration/',
   'Gold/Silver/Bronze medals', 'online', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000004',
   'Singapore Physics Olympiad (SPhO)',
   'Singapore''s national physics olympiad for pre-university students, organised by the Institute of Physics Singapore. It comprises a theory and an experimental round and helps select Singapore''s Asian and International Physics Olympiad teams.',
   'Science', 'Institute of Physics Singapore (IPS)',
   (current_date + interval '25 days')::date, (current_date + interval '55 days')::date,
   'JC / pre-university (ages 15-18)', 'https://ipssingapore.org/events/SPhO.html',
   'Gold/Silver/Bronze medals', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000005',
   'National Olympiad in Informatics (NOI) Singapore',
   'Singapore''s national competitive programming olympiad, hosted by the NUS School of Computing. Students solve algorithmic problems, and top performers are selected to train for and represent Singapore at the International Olympiad in Informatics.',
   'Tech', 'NUS School of Computing',
   (current_date + interval '10 days')::date, (current_date + interval '38 days')::date,
   'Secondary / JC (under 20)', 'https://noisg.comp.nus.edu.sg/noi/',
   'Gold/Silver/Bronze medals', 'onsite', 'Singapore', null, true, true),

  ('33333333-0000-0000-0000-000000000006',
   'National Olympiad in Artificial Intelligence (NOAI)',
   'Singapore''s national AI olympiad organised by AI Singapore, testing fundamental AI concepts and Python programming. It consists of an online preliminary round and a final assessment, and selects the national team for the International Olympiad in AI.',
   'Tech', 'AI Singapore',
   (current_date + interval '20 days')::date, (current_date + interval '50 days')::date,
   'Secondary / JC (MOE students)', 'https://learn.aisingapore.org/national-olympiad-in-artificial-intelligence-2/',
   'Gold/Silver/Bronze medals', 'hybrid', 'Singapore', null, true, true),

  ('33333333-0000-0000-0000-000000000007',
   'Singapore Astronomy Olympiad (SAO)',
   'A national olympiad on astronomy and astrophysics that selects candidates to represent Singapore at the International Olympiad on Astronomy and Astrophysics. Round 1 is a computerised quiz open to all eligible students, with an invitational Round 2.',
   'Science', 'Astronomy.SG / Hwa Chong Institution',
   (current_date + interval '16 days')::date, (current_date + interval '44 days')::date,
   'Under 20, up to Grade 12 (Secondary / JC)', 'https://astronomy.sg/singapore-astronomy-olympiad/',
   'Gold/Silver/Bronze medals', 'hybrid', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000008',
   'Tan Kah Kee Young Inventors'' Award (TKKYIA)',
   'A long-running invention and innovation competition organised by the Tan Kah Kee Foundation with support from MOE and Science Centre Singapore. Students design innovative solutions applying scientific principles, entering as individuals or teams of up to three.',
   'STEM', 'Tan Kah Kee Foundation',
   (current_date + interval '30 days')::date, (current_date + interval '75 days')::date,
   'Secondary / JC / Polytechnic / ITE', 'https://tkkyia.awardsplatform.com/',
   'Cash awards and medals', 'hybrid', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000009',
   'A*STAR Science Award (Upper Secondary)',
   'An award by the Agency for Science, Technology and Research for Singaporean Secondary 3 students with strong aptitude in science and mathematics. Recipients take part in a Research Exposure Programme and receive a monetary allowance.',
   'Science', 'A*STAR (Agency for Science, Technology and Research)',
   (current_date + interval '34 days')::date, (current_date + interval '80 days')::date,
   'Secondary 3 (Singaporean)', 'https://www.a-star.edu.sg/scholarships/home/student-awards/astar-science-award-upper-sec',
   'S$500 allowance + research programme', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000010',
   'Singapore Amazing Flying Machine Competition (SAFMC)',
   'A national aeronautics and drone competition organised by DSO National Laboratories and Science Centre Singapore. Categories include paper planes, bungee-launched gliders and programmable drone challenges completed in teams.',
   'STEM', 'DSO National Laboratories & Science Centre Singapore',
   (current_date + interval '12 days')::date, (current_date + interval '42 days')::date,
   'Secondary / JC (full-time students)', 'https://www.safmc.com.sg/registration/',
   'Trophies and medals', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000011',
   'National Robotics Competition (NRC)',
   'Singapore''s flagship robotics competition organised by Science Centre Singapore since 1999, with a new mission theme each year. Teams design and program robots to complete challenges aligned with the UN Sustainable Development Goals.',
   'STEM', 'Science Centre Singapore',
   (current_date + interval '8 days')::date, (current_date + interval '36 days')::date,
   'Secondary / JC (school teams)', 'https://www.science.edu.sg/for-schools/competitions/national-robotics-competition',
   'Trophies and medals', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000012',
   'Cyberthon',
   'An annual cybersecurity and AI competition for JC students organised by Hwa Chong Institution with CSIT and the Digital and Intelligence Service. It features online cybersecurity challenges and an on-site fiesta of activities.',
   'Tech', 'Hwa Chong Institution, CSIT & DIS',
   (current_date + interval '15 days')::date, (current_date + interval '30 days')::date,
   'JC / MI Year 1-3 (ages 16-18)', 'https://cyberthon.sg/',
   'Trophies and medals', 'hybrid', 'Singapore', null, true, true),

  ('33333333-0000-0000-0000-000000000013',
   'World Robot Olympiad (WRO) — Singapore',
   'An international robotics competition with a Singapore national round organised by Space Faculty. Categories such as RoboMission and Future Innovators run across age groups, with national champions advancing to the WRO International Final.',
   'STEM', 'WRO Association / Space Faculty (Singapore)',
   (current_date + interval '26 days')::date, (current_date + interval '65 days')::date,
   'Junior High and Senior High age groups (up to ~19)', 'https://spacefaculty.asia/wro/',
   'Medals + international final qualification', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000014',
   'VEX Robotics Competition (Singapore)',
   'A globally-run robotics competition (VEX IQ and VEX V5) with Singapore national championships that qualify teams for the VEX Robotics World Championship. Teams design, build and program robots to complete a new game challenge each season.',
   'STEM', 'REC Foundation (VEX Robotics Singapore)',
   (current_date + interval '32 days')::date, (current_date + interval '70 days')::date,
   'Secondary / JC (ages 12-18)', 'https://www.robotevents.com/robot-competitions/vex-robotics-competition',
   'Trophies + Worlds qualification', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000015',
   'FIRST LEGO League (FLL) Challenge',
   'A global STEM and robotics programme in which teams research a real-world problem and build and program a LEGO robot to complete missions. Singapore runs its own regional tournaments with top teams advancing internationally.',
   'STEM', 'FIRST / Duck Learning (Singapore)',
   (current_date + interval '19 days')::date, (current_date + interval '58 days')::date,
   'Ages 9-16 (Secondary lower levels)', 'https://www.firstlegoleague.sg/registration/',
   'Trophies + international championship spots', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000016',
   'Australian Mathematics Competition (AMC)',
   'One of the world''s largest school mathematics competitions, run by the Australian Maths Trust and open to Singapore students through registered schools. It is a multiple-choice problem-solving contest across year levels.',
   'Math', 'Australian Maths Trust (AMT)',
   (current_date + interval '24 days')::date, (current_date + interval '54 days')::date,
   'Years 7-12 (Secondary / JC)', 'https://amt.edu.au/amc',
   'High Distinction / Distinction / Credit certificates', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000017',
   'International Mathematical Olympiad (IMO)',
   'The world championship mathematics competition for secondary school students, with each country sending a team of up to six. Singapore selects its team through its national olympiad pipeline.',
   'Math', 'IMO Foundation (national team via Singapore Mathematical Society)',
   (current_date + interval '45 days')::date, (current_date + interval '120 days')::date,
   'Secondary / JC (under 20, pre-university)', 'https://www.imo-official.org/',
   'Gold/Silver/Bronze medals + honourable mentions', 'onsite', 'Global', null, true, true),

  ('33333333-0000-0000-0000-000000000018',
   'International Olympiad in Informatics (IOI)',
   'The premier international competitive programming olympiad for secondary students, with each country sending up to four contestants selected through national contests such as Singapore''s NOI.',
   'Tech', 'International Olympiad in Informatics',
   (current_date + interval '50 days')::date, (current_date + interval '130 days')::date,
   'Secondary school (under 20, pre-university)', 'https://ioinformatics.org/',
   'Gold/Silver/Bronze medals', 'onsite', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000019',
   'International Chemistry Olympiad (IChO)',
   'A prestigious international chemistry competition featuring theoretical and laboratory practical examinations, with each country fielding a team of four. Students qualify through their national chemistry olympiad.',
   'Science', 'International Chemistry Olympiad',
   (current_date + interval '48 days')::date, (current_date + interval '125 days')::date,
   'Secondary school (under 20, not in university)', 'https://www.ichosc.org/',
   'Gold/Silver/Bronze medals', 'onsite', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000020',
   'Regeneron International Science and Engineering Fair (ISEF)',
   'The world''s largest pre-college STEM research competition, run by the Society for Science, drawing finalists from hundreds of affiliated fairs in over 60 countries. Singapore students qualify via SSEF.',
   'Science', 'Society for Science',
   (current_date + interval '55 days')::date, (current_date + interval '140 days')::date,
   'Grades 9-12 (ages ~14-18)', 'https://www.societyforscience.org/isef/',
   'Up to US$75,000 grand awards', 'onsite', 'Global', null, true, true),

  -- ---- Debate / MUN / Public Speaking / Academic ---------------------------
  ('33333333-0000-0000-0000-000000000021',
   'Singapore Model United Nations (SMUN)',
   'The flagship MUN conference of the Political Science Society at NUS. Delegates debate global issues across a range of committees, with councils open to secondary and JC students.',
   'Debate', 'Political Science Society, National University of Singapore',
   (current_date + interval '28 days')::date, (current_date + interval '68 days')::date,
   'Secondary / JC (approx. grades 7-12)', 'https://www.singaporemun.org/',
   'Best Delegate and committee awards', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000022',
   'NTU Model United Nations (NTUMUN)',
   'An annual Model UN conference organised by students at Nanyang Technological University. It brings together secondary, JC and tertiary delegates to simulate international diplomacy across multiple committees.',
   'Debate', 'Nanyang Technological University',
   (current_date + interval '33 days')::date, (current_date + interval '72 days')::date,
   'Secondary / JC / tertiary (ages 15+)', 'https://www.ntumodelun.com/',
   'Best Delegate and committee awards', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000023',
   'Yale Model United Nations Singapore (YMUNS)',
   'The Singapore edition of Yale University''s Model UN conference, staffed by Yale students. It offers secondary and JC delegates an internationally run MUN experience with committees on global affairs.',
   'Debate', 'Yale International Relations Association',
   (current_date + interval '36 days')::date, (current_date + interval '78 days')::date,
   'Secondary / JC (ages 14-18)', 'https://ymuns.org/register',
   'Delegate awards and recognition', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000024',
   'THIMUN Singapore',
   'An affiliated conference of The Hague International Model United Nations. Schools from across Asia send delegations of secondary and JC students to debate in a large, internationally recognised MUN setting.',
   'Debate', 'THIMUN Foundation',
   (current_date + interval '40 days')::date, (current_date + interval '90 days')::date,
   'Secondary / JC students', 'https://singapore.thimun.org/singapore-conference/',
   'Recognition and conference participation', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000025',
   'Harvard Model United Nations (HMUN)',
   'The oldest and largest high school MUN conference, held each January in Boston and staffed by Harvard students, drawing 3,000+ delegates worldwide. Singapore schools regularly send delegations to compete.',
   'Debate', 'Harvard International Relations Council',
   (current_date + interval '52 days')::date, (current_date + interval '135 days')::date,
   'High school, ages 13+', 'https://www.harvardmun.org/application-process',
   'Best Delegate and diplomacy awards', 'onsite', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000026',
   'World Individual Debating and Public Speaking Championships (WIDPSC)',
   'An annual international tournament individually ranking high school students in debating and public speaking. Competitors take part in events such as parliamentary debate, impromptu speaking, interpretive reading and persuasive speaking.',
   'Debate', 'WIDPSC (rotating host schools)',
   (current_date + interval '44 days')::date, (current_date + interval '110 days')::date,
   'High school students (ages 14-18)', 'https://sites.google.com/view/worldindividuals/home',
   'John Robinson Award for overall champion', 'onsite', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000027',
   'World Scholar''s Cup',
   'A global academic team competition combining collaborative writing, debate, the Scholar''s Challenge quiz and the Scholar''s Bowl, held across Regional Rounds (including a Singapore Round), Global Rounds and the Tournament of Champions.',
   'Other', 'DemiDec / World Scholar''s Cup',
   (current_date + interval '21 days')::date, (current_date + interval '62 days')::date,
   'Junior (ages 11-14) and Senior (ages 15-18) divisions', 'https://www.scholarscup.org/calendar/',
   'Medals, trophies and advancement to Global Round', 'hybrid', 'Both', null, true, true),

  -- ---- Business / Entrepreneurship / Finance / Economics -------------------
  ('33333333-0000-0000-0000-000000000028',
   'Diamond Challenge',
   'A global entrepreneurship competition run by Horn Entrepreneurship at the University of Delaware, where teams develop an original business or social venture concept across a Business Innovation or Social Innovation track.',
   'Business', 'Horn Entrepreneurship, University of Delaware',
   (current_date + interval '35 days')::date, (current_date + interval '95 days')::date,
   'High school, ages 14-18', 'https://diamondchallenge.org/competition/',
   'US$100K prize pool (up to $12,000 grand prize per track)', 'hybrid', 'Global', null, true, true),

  ('33333333-0000-0000-0000-000000000029',
   'Wharton Global High School Investment Competition',
   'A free, experiential investing competition where student teams act as financial advisors managing a virtual portfolio for a hypothetical client. Top teams advance to a global finale at Wharton.',
   'Business', 'Wharton Global Youth Program, University of Pennsylvania',
   (current_date + interval '27 days')::date, (current_date + interval '85 days')::date,
   'Grades 9-12 (ages 14-18)', 'https://globalyouth.wharton.upenn.edu/competitions/investment-competition/register-now/',
   'Global finale at Wharton and recognition', 'hybrid', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000030',
   'DECA International Career Development Conference (ICDC)',
   'The culminating event of DECA''s competitive events program in marketing, finance, hospitality, management and entrepreneurship. Competitors qualify through school and regional rounds and complete role-plays, case studies and written projects.',
   'Business', 'DECA Inc.',
   (current_date + interval '42 days')::date, (current_date + interval '115 days')::date,
   'High school DECA members (ages 14-18)', 'https://www.deca.org/compete',
   'International recognition and awards', 'onsite', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000031',
   'National Economics & Financial Management Challenge (NEFMC)',
   'An annual competition run by the NUS Economics Society for pre-tertiary students in Singapore, sponsored by the Monetary Authority of Singapore. Teams face an online economics and finance assessment and a live stock-market trading simulation.',
   'Business', 'NUS Economics Society',
   (current_date + interval '17 days')::date, (current_date + interval '47 days')::date,
   'Pre-tertiary (Secondary / JC) students', 'https://www.nuseconsoc.com/nefmc',
   'Cash prizes and trophies', 'hybrid', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000032',
   'International Economics Olympiad (IEO)',
   'A global economics competition assessing students in economics, finance and business case analysis, with national teams selected through country-level qualifiers and an OpenTrack option open to all.',
   'Business', 'International Economics Olympiad',
   (current_date + interval '38 days')::date, (current_date + interval '100 days')::date,
   'Under 20, not yet graduated high school', 'https://ieo-official.org/opentrack',
   'Gold, silver and bronze medals', 'hybrid', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000033',
   'John Locke Institute Global Essay Prize',
   'A prestigious international essay competition inviting pre-university students to write on set questions across subjects including Economics, Politics, Philosophy and History. Essays are capped at 2,000 words and judged on knowledge, reasoning and style.',
   'Other', 'John Locke Institute',
   (current_date + interval '46 days')::date, (current_date + interval '105 days')::date,
   'Under 19 (junior category under 15)', 'https://www.johnlockeinstitute.com/essay-competition',
   'Scholarships and academic recognition', 'online', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000034',
   'The Marshall Society Essay Competition',
   'An annual economics essay competition run by the Marshall Society, the economics society of the University of Cambridge. Pre-university students worldwide write around 1,250 words on a set economics question, judged on logic, evidence and originality.',
   'Business', 'The Marshall Society, University of Cambridge',
   (current_date + interval '31 days')::date, (current_date + interval '82 days')::date,
   'Pre-university students worldwide', 'https://marshallsociety.com/essay-competition/',
   'Cash prizes and publication', 'online', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000035',
   'The Queen''s Commonwealth Writing Competition',
   'The world''s oldest international schools writing competition, run by the Royal Commonwealth Society since 1883 and open to young people across the Commonwealth. Entrants submit a written piece under 1,000 words on a set theme.',
   'Other', 'Royal Commonwealth Society',
   (current_date + interval '29 days')::date, (current_date + interval '88 days')::date,
   'Under 18 in a Commonwealth country', 'https://www.royalcwsociety.org/writing-competition',
   'Winners invited to London for an award ceremony', 'online', 'Global', null, true, false),

  -- ---- Arts / Film / Photography / Music / Design --------------------------
  ('33333333-0000-0000-0000-000000000036',
   'ciNE65 Movie Makers Awards',
   'A short-film competition organised by Nexus (MINDEF) and mm2 Entertainment encouraging young film-makers to tell stories that deepen their connection to Singapore. It includes a dedicated Student Category and an Inter-school Challenge Trophy.',
   'Arts', 'Nexus (Ministry of Defence) and mm2 Entertainment',
   (current_date + interval '37 days')::date, (current_date + interval '92 days')::date,
   'Open to students and members of the public in Singapore', 'https://www.cine65.sg/',
   'Winner directs a feature film with mm2; technical awards', 'hybrid', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000037',
   'Singapore Youth Film Festival (SYFF)',
   'A national platform presented by *SCAPE celebrating young filmmakers, evolved from the National Youth Film Awards established in 2015. It features a Student Category and partners with the Singapore International Film Festival.',
   'Arts', '*SCAPE',
   (current_date + interval '23 days')::date, (current_date + interval '63 days')::date,
   'Full-time students aged 35 and below in Singapore', 'https://syff.sg/',
   'Awards across categories; festival official selection', 'hybrid', 'Singapore', null, true, true),

  ('33333333-0000-0000-0000-000000000038',
   'Toyota Dream Car Art Contest',
   'A global children''s art competition inviting young people to draw their "dream car" and imagine the future of mobility. It runs as a National Contest in each country, with top works advancing to the World Contest in Japan.',
   'Arts', 'Toyota (Borneo Motors Singapore)',
   (current_date + interval '41 days')::date, (current_date + interval '98 days')::date,
   'Children and youth aged 15 and under', 'https://www.toyota-dreamcarart.com/',
   'National awards plus global recognition in Japan', 'onsite', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000039',
   'Student Visual Storytelling Awards',
   'An annual photography and film competition for students run by Objectifs Centre for Photography and Film. Categories include Student Photographer of the Year, Student Film of the Year and Photo Team of the Year, with winning works exhibited.',
   'Arts', 'Objectifs — Centre for Photography and Film',
   (current_date + interval '20 days')::date, (current_date + interval '56 days')::date,
   'Students turning 13-18, in Singapore schools', 'https://www.objectifs.com.sg/student-visual-storytelling-awards-2026/',
   'Cash prizes and exhibition at Objectifs', 'hybrid', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000040',
   'CDL Singapore Young Photographer Award (SYPA)',
   'A national youth photography award encouraging young photographers to explore a yearly theme through Junior and Youth categories. Winning works are showcased publicly.',
   'Arts', 'City Developments Limited (CDL) and partners',
   (current_date + interval '34 days')::date, (current_date + interval '84 days')::date,
   'Youths aged 13-25 (Junior 13-18, Youth 19-25)', 'https://sypa.sg/',
   'Prizes worth over S$8,000', 'hybrid', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000041',
   'Our Schools, Our Stories Photo & Video Contest',
   'An MOE contest inviting students and the school community to capture meaningful moments of school life through photos and videos. Entries must be original works taken within the specified contest period.',
   'Arts', 'Ministry of Education (MOE)',
   (current_date + interval '13 days')::date, (current_date + interval '43 days')::date,
   'Students and members of the Singapore school community', 'https://www.moe.gov.sg/our-schools-our-stories/contest',
   'Prizes across photo and video categories', 'online', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000042',
   'Super 24 Dance Competition',
   'A distinctive mega-crew dance competition where teams of 24 members perform a 90-second routine within an 8x8 metre square, judged from all four sides. Presented by O School with Primary, Secondary, Tertiary and Open divisions.',
   'Arts', 'O School',
   (current_date + interval '39 days')::date, (current_date + interval '86 days')::date,
   'School crews (Secondary, Tertiary) and Open category', 'https://www.super24sg.com/',
   'Championship title of "Super 24" and division awards', 'onsite', 'Both', null, true, false),

  ('33333333-0000-0000-0000-000000000043',
   'Singapore International Original Comics Competition (SGIOCC)',
   'Part of the Singapore Original Comic Festival, this competition celebrates young comic creators worldwide through original illustration and storytelling across junior, children and youth categories.',
   'Arts', 'Singapore International Original Comics Festival',
   (current_date + interval '43 days')::date, (current_date + interval '96 days')::date,
   'Youth categories to age 19', 'https://sgiocc.com/',
   'Category awards and exhibition of winning works', 'online', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000044',
   'Live On Festival Design Competition',
   'A design competition run under the national Live On movement promoting organ donation and transplant awareness. Students create designs around annual themes, with winning designs printed on merchandise.',
   'Arts', 'Live On (Ministry of Health / National Organ Transplant Unit)',
   (current_date + interval '26 days')::date, (current_date + interval '66 days')::date,
   'Singapore residents aged 13 and above', 'https://festival.liveon.gov.sg/competition-information/design-competition/',
   'Winning designs printed on merchandise; category prizes', 'online', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000045',
   'Singapore Chinese Music Competition (SCMC)',
   'Organised by the Singapore Chinese Orchestra to develop young musicians and raise musical standards. It features Solo and Ensemble sections across Chinese instruments, with age-based categories.',
   'Arts', 'Singapore Chinese Orchestra (SCO)',
   (current_date + interval '47 days')::date, (current_date + interval '102 days')::date,
   'Young musicians across age categories (Junior to Intermediate)', 'https://sco.com.sg/about-us/singapore-chinese-music-competition-scmc/',
   'Cash prizes and performance opportunities', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000046',
   'Zuntra UI/UX Design Awards',
   'A UI/UX design competition providing a platform for emerging design thinkers and creators to showcase innovation through meaningful digital experiences. It is open to both students and professionals.',
   'Arts', 'Zuntra Digital',
   (current_date + interval '49 days')::date, (current_date + interval '108 days')::date,
   'Students and professionals in design', 'https://www.zuntra.com/uiuxdesignawards2026-zuntra',
   'Recognition and awards for winning designs', 'online', 'Global', null, true, false),

  ('33333333-0000-0000-0000-000000000047',
   'Singapore International Choral Festival (SICF) Competition',
   'An international choral festival held in Singapore featuring a competition across multiple choral categories, including youth and school choirs. Choirs perform live before an expert jury.',
   'Arts', 'Singapore International Choral Festival',
   (current_date + interval '53 days')::date, (current_date + interval '118 days')::date,
   'Choirs including youth and school categories', 'https://sicf.sg/en/competition/',
   'Category awards and Grand Prix', 'onsite', 'Both', null, true, false),

  -- ---- Sports / Games / Other ----------------------------------------------
  ('33333333-0000-0000-0000-000000000048',
   'National School Games (NSG)',
   'Singapore''s largest annual youth sports event, organised by MOE and the schools'' sports councils. NSG features tens of thousands of student-athletes from over 300 schools competing across 29 sports.',
   'Sports', 'Ministry of Education (MOE) and Singapore Schools Sports Councils',
   (current_date + interval '9 days')::date, (current_date + interval '39 days')::date,
   'Students representing their schools (Secondary and JC/CI)', 'https://nsg.moe.edu.sg/home',
   'Divisional and national championship medals and titles', 'onsite', 'Singapore', null, true, true),

  ('33333333-0000-0000-0000-000000000049',
   'National Schools Individual Chess Championships (NSI)',
   'The largest schools chess event in Singapore, organised annually by the Singapore Chess Federation. Players compete across six age groups in a FIDE-rated tournament.',
   'Other', 'Singapore Chess Federation',
   (current_date + interval '11 days')::date, (current_date + interval '41 days')::date,
   'Students across six age groups (under 8 to under 20)', 'https://singaporechess.org.sg/77th-nsi-2026/',
   'Age-group champion titles and trophies', 'onsite', 'Singapore', null, true, false),

  ('33333333-0000-0000-0000-000000000050',
   'National Youth Tech Championship (NYTC)',
   'An IMDA-organised national competition engaging youths in tech skills such as coding, AI and digital media through challenges and bootcamps. It is a highlight event promoting digital talent among students.',
   'Other', 'Infocomm Media Development Authority (IMDA)',
   (current_date + interval '18 days')::date, (current_date + interval '49 days')::date,
   'Youths and students in Singapore', 'https://www.imda.gov.sg/activities/activities-catalogue/national-youth-tech-championship',
   'Championship awards and tech development opportunities', 'hybrid', 'Singapore', null, true, false)
on conflict (id) do nothing;
